# Generated by Django 3.1.7 on 2021-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=1111111111, max_length=50),
            preserve_default=False,
        ),
    ]
